name: qmm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - numpy
  - sympy
  - networkx
  - numba
  - pandas
  - seaborn
  - matplotlib
  - pip
  - pip:
    - build
    - twine
    - ruff
