name: qmm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - pytest
  - numpy
  - networkx
  - pandas
  - numba
  - sympy
  - graphviz
  - seaborn
  - matplotlib
  - jupyter
  